<a href="https://colab.research.google.com/github/Raihan151/Simulation-Modeling/blob/main/SIM_Lab1_Raihan_151.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
# Sample scalar and array inputs
scalar = 3.7
arr = np.array([10.48, 20.89, 30.54, 40.33, 50.62,60.12])

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))  # Normalized and Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)

# Exponential and logarithm
exp_values = np.exp(arr)
log_values = np.log(arr)  # Natural logarithm

# Absolute value and square root
abs_values = np.abs(arr)
sqrt_values = np.sqrt(arr)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(arr, 2)

# Rounding functions
round_values = np.round(arr)
floor_values = np.floor(arr)
ceil_values = np.ceil(arr)

# Display results
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)
print("exp:", exp_values)
print("log:", log_values)
print("abs:", abs_values)
print("sqrt:", sqrt_values)
print("rem:", rem_values)
print("round:", round_values)
print("floor:", floor_values)
print("ceil:", ceil_values)

sin: [-0.87000972  0.89172776 -0.76813708  0.48879197  0.34713795 -0.41663408]
cos: [-0.49303457 -0.4525722   0.64028543 -0.87240037  0.93781408 -0.90907428]
tan: [ 1.76460188 -1.97035468 -1.19967915 -0.560284    0.37015647  0.45830587]
asin: [0.17521315 0.35487347 0.53284274 0.73532069 1.00094779 1.57079633]
acos: [1.39558317 1.21592286 1.03795359 0.83547564 0.56984853 0.        ]
atan: [1.47566451 1.52296305 1.53806408 1.54600597 1.55104386 1.55416446]
exp: [3.55964075e+04 1.18144015e+09 1.83380637e+13 3.27413404e+17
 9.63799450e+21 1.28760974e+26]
log: [2.34946868 3.03927058 3.4190373  3.69709561 3.92434676 4.09634256]
abs: [10.48 20.89 30.54 40.33 50.62 60.12]
sqrt: [3.23728281 4.57055795 5.52630075 6.35059052 7.11477336 7.75370879]
rem: [0.48 0.89 0.54 0.33 0.62 0.12]
round: [10. 21. 31. 40. 51. 60.]
floor: [10. 20. 30. 40. 50. 60.]
ceil: [11. 21. 31. 41. 51. 61.]


In [ ]:
# Creating a 2x2 matrix
matrix = np.array([[1, 2], [3, 4]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)

sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[1 2]
 [3 4]]

sin:
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]

cos:
 [[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]

tan:
 [[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]]

asine:
 [[0.25268026 0.52359878]
 [0.84806208 1.57079633]]

acosine:
 [[1.31811607 1.04719755]
 [0.72273425 0.        ]]

atangent:
 [[0.78539816 1.10714872]
 [1.24904577 1.32581766]]

exp:
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]

log (natural):
 [[0.         0.69314718]
 [1.09861229 1.38629436]]

abs:
 [[1 2]
 [3 4]]

sqrt:
 [[1.         1.41421356]
 [1.73205081 2.        ]]

rem (remainder when divided by 2):
 [[1 0]
 [1 0]]

round:
 [[1 2]
 [3 4]]

floor:
 [[1. 2.]
 [3. 4.]]

ceil:
 [[1. 2.]
 [3. 4.]]


In [ ]:
# 3x2 matrix
matrix = np.array([[1, 2],[3, 4],[5, 6]])

    # Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)

# Inverse trigonometric functions
# Normalize matrix values to [-1, 1] for asin and acos
normalized_matrix = np.clip(matrix / np.max(matrix), -1, 1)
asin_values = np.arcsin(normalized_matrix)
acos_values = np.arccos(normalized_matrix)
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by 2
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasin:\n", asin_values)
print("\nacos:\n", acos_values)
print("\natan:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[1 2]
 [3 4]
 [5 6]]

sin:
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155 ]]

cos:
 [[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]
 [ 0.28366219  0.96017029]]

tan:
 [[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]
 [-3.38051501 -0.29100619]]

asin:
 [[0.16744808 0.33983691]
 [0.52359878 0.72972766]
 [0.98511078 1.57079633]]

acos:
 [[1.40334825 1.23095942]
 [1.04719755 0.84106867]
 [0.58568554 0.        ]]

atan:
 [[0.78539816 1.10714872]
 [1.24904577 1.32581766]
 [1.37340077 1.40564765]]

exp:
 [[  2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003]
 [148.4131591  403.42879349]]

log (natural):
 [[0.         0.69314718]
 [1.09861229 1.38629436]
 [1.60943791 1.79175947]]

abs:
 [[1 2]
 [3 4]
 [5 6]]

sqrt:
 [[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]

rem (remainder when divided by 2):
 [[1 0]
 [1 0]
 [1 0]]

round:
 [[1 2]
 [3 4]
 [5 6]]

floor:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]

ceil:
 [[1. 2.]
 [3. 

In [ ]:
# 2×3 matrix with float values
mat = np.array([[2.1, 4.7, 1.3],[5.9, 0.4, 3.8]])




print("Matrix:\n", mat)

# 1. Maximum and minimum values with indices
max_value = np.max(mat)
min_value = np.min(mat)

max_index = np.unravel_index(np.argmax(mat), mat.shape)
min_index = np.unravel_index(np.argmin(mat), mat.shape)



# 2. Vector length (total number of elements)
vec_length = mat.size


# 3. Sorting Row-wise descending sort
sorted_row_desc = np.sort(mat, axis=1)[:, ::-1]


# Entire matrix descending sort
sorted_entire_desc = np.sort(mat.flatten())[::-1]


# 4. Sum and Product
sum_values = np.sum(mat)
prod_values = np.prod(mat)


# 5. Median, Mean, Standard Deviation
median_value = np.median(mat)
mean_value = np.mean(mat)
std_dev = np.std(mat)
print("Matrix:\n", mat)
print("\nMax value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("\nVector length:", vec_length)
print("\nRow-wise sorted (descending):\n", sorted_row_desc)
print("\nEntire matrix sorted (descending):", sorted_entire_desc)
print("\nSum of elements:", sum_values)
print("Product of elements:", prod_values)
print("\nMedian value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)


Matrix:
 [[2.1 4.7 1.3]
 [5.9 0.4 3.8]]
Matrix:
 [[2.1 4.7 1.3]
 [5.9 0.4 3.8]]

Max value: 5.9 at index (np.int64(1), np.int64(0))
Min value: 0.4 at index (np.int64(1), np.int64(1))

Vector length: 6

Row-wise sorted (descending):
 [[4.7 2.1 1.3]
 [5.9 3.8 0.4]]

Entire matrix sorted (descending): [5.9 4.7 3.8 2.1 1.3 0.4]

Sum of elements: 18.200000000000003
Product of elements: 115.06840800000002

Median value: 2.95
Mean value: 3.0333333333333337
Standard deviation: 1.9318960174456137
